ci:
  autoupdate_schedule: "quarterly"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-builtin-literals
  - id: check-executables-have-shebangs
  - id: check-json
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    files: ^asapdiscovery
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    files: ^asapdiscovery
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    files: ^asapdiscovery
- repo: https://github.com/asottile/pyupgrade
  rev: 'v3.3.1'
  hooks:
  - id: pyupgrade
    args:
    - --py39-plus
