# readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"

sphinx:
   configuration: docs/conf.py

conda:
  environment: docs/requirements.yaml

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: asapdiscovery-alchemy
    - method: pip
      path: asapdiscovery-data
    - method: pip
      path: asapdiscovery-dataviz
    - method: pip
      path: asapdiscovery-docking
    - method: pip
      path: asapdiscovery-ml
    - method: pip
      path: asapdiscovery-modeling
    - method: pip
      path: asapdiscovery-simulation
