# install asapdiscovery repo
pip install -e asapdiscovery-data
pip install -e asapdiscovery-cli
pip install -e asapdiscovery-simulation
pip install -e asapdiscovery-modeling
pip install -e asapdiscovery-dataviz
pip install -e asapdiscovery-docking
pip install -e asapdiscovery-ml
pip install -e asapdiscovery-alchemy
