import os
from collections import namedtuple
from functools import reduce
from pathlib import Path
from typing import Union

from asapdiscovery.data.openeye import (
    load_openeye_pdb,
    oechem,
    oedocking,
    oespruce,
    openeye_perceive_residues,
)
from asapdiscovery.modeling.schema import MoleculeComponent, MoleculeFilter


def add_seqres_to_openeye_protein(
    prot: oechem.OEGraphMol, seqres: str = None
) -> oechem.OEGraphMol:
    """
    Adds the SEQRES metadata to the given protein structure.

    Args:
    - prot (oechem.OEDesignUnit): the protein structure to add the SEQRES metadata to.
    """
    # Add SEQRES entries if they're not present
    if (not oechem.OEHasPDBData(prot, "SEQRES")) and seqres:
        for seqres_line in seqres.split("\n"):
            if seqres_line != "":
                oechem.OEAddPDBData(prot, "SEQRES", seqres_line[6:])
    return prot


def spruce_protein(
    initial_prot: oechem.OEGraphMol,
    return_du=False,
    seqres: str = None,
    loop_db: Path = None,
    site_residue=None,  # e.g. "HIS:41: :A:0: "
) -> oechem.OEDesignUnit or oechem.OEGraphMol:
    """
    Applies the OESpruce protein preparation pipeline to the given protein structure.

    Args:
    - initial_prot (oechem.OEMol): the input protein structure to be prepared.
    - return_du (bool, optional): whether to return a design unit (DU) as the output. If True, the function will
      return the DU generated by the OESpruce pipeline; if False, the function will return the prepared protein
      structure as an oechem.OEGraphMol. Default is False.
    - seqres (str, optional): the SEQRES string of the protein. If provided, the SEQRES metadata will be added
      to the structure before applying the OESpruce pipeline. Default is None.
    - loop_db (str, optional): the filename of the loop database to be used by the OESpruce pipeline. If provided,
      the pipeline will include loop building step. Default is None.
    - site_residue (str, optional): the site residue used to define the binding site of the protein. Default is
      "HIS:41: :A:0: ". This is necessary when there is no ligand in the input structure, otherwise OpenEye will not
      know where to put the binding site.

    Returns:
    - oechem.OEMol: the prepared protein structure, or a DU generated by the OESpruce pipeline if return_du is True.
      If design unit preparation fails, it will return the prepared protein structure instead.
    """
    from asapdiscovery.data.openeye import openeye_perceive_residues

    # Add Hs to prep protein and ligand
    oechem.OEAddExplicitHydrogens(initial_prot)

    # Set up DU building options
    opts = oespruce.OEMakeDesignUnitOptions()
    opts.SetSuperpose(False)
    # Options set from John's function ########################################
    # (https://github.com/FoldingAtHome/covid-moonshot/blob/454098f4255467f4655102e0330ebf9da0d09ccb/synthetic-enumeration/sprint-14-quinolones/00-prep-receptor.py)
    opts.GetPrepOptions().SetStrictProtonationMode(True)
    # set minimal number of ligand atoms to 5, e.g. a 5-membered ring fragment\
    opts.GetSplitOptions().SetMinLigAtoms(5)

    # also consider alternate locations outside binding pocket, important for later filtering
    opts.GetPrepOptions().GetEnumerateSitesOptions().SetCollapseNonSiteAlts(True)

    # alignment options, only matches are important
    opts.GetPrepOptions().GetBuildOptions().GetLoopBuilderOptions().SetSeqAlignMethod(
        oechem.OESeqAlignmentMethod_Identity
    )
    opts.GetPrepOptions().GetBuildOptions().GetLoopBuilderOptions().SetSeqAlignGapPenalty(
        -1
    )
    opts.GetPrepOptions().GetBuildOptions().GetLoopBuilderOptions().SetSeqAlignExtendPenalty(
        0
    )

    # Both N- and C-termini should be zwitterionic
    # Mpro cleaves its own N- and C-termini
    # See https://www.pnas.org/content/113/46/12997
    opts.GetPrepOptions().GetBuildOptions().SetCapNTermini(False)
    opts.GetPrepOptions().GetBuildOptions().SetCapCTermini(False)
    # Don't allow truncation of termini, since force fields don't have
    #  parameters for this
    opts.GetPrepOptions().GetBuildOptions().GetCapBuilderOptions().SetAllowTruncate(
        False
    )
    # Set Build Loop and Sidechain Opts
    sc_opts = oespruce.OESidechainBuilderOptions()

    loop_opts = oespruce.OELoopBuilderOptions()
    loop_opts.SetSeqAlignMethod(oechem.OESeqAlignmentMethod_Identity)
    loop_opts.SetSeqAlignGapPenalty(-1)
    loop_opts.SetSeqAlignExtendPenalty(0)

    # Allow for adding residues at the beginning/end if they're missing
    loop_opts.SetBuildTails(True)

    opts.GetPrepOptions().GetBuildOptions().GetLoopBuilderOptions().SetBuildTails(True)

    if loop_db is not None:
        print("Adding loop db")
        loop_opts.SetLoopDBFilename(str(loop_db))

    # Structure metadata object
    metadata = oespruce.OEStructureMetadata()

    # Add SEQRES metadata
    if seqres:
        print("adding seqres")
        all_prot_chains = {
            res.GetExtChainID()
            for res in oechem.OEGetResidues(initial_prot)
            if (res.GetName() != "LIG") and (res.GetName() != "HOH")
        }
        for chain in all_prot_chains:
            seq_metadata = oespruce.OESequenceMetadata()
            seq_metadata.SetChainID(chain)
            seq_metadata.SetSequence(seqres)
            metadata.AddSequenceMetadata(seq_metadata)

    # Construct spruce filter
    spruce_opts = oespruce.OESpruceFilterOptions()
    spruce = oespruce.OESpruceFilter(spruce_opts, opts)

    # Spruce!
    from asapdiscovery.data.openeye import oegrid

    # This object is for some reason needed in order to run spruce
    grid = oegrid.OESkewGrid()

    oespruce.OEBuildLoops(initial_prot, metadata, sc_opts, loop_opts)
    oespruce.OEBuildSidechains(initial_prot, sc_opts)
    oechem.OEPlaceHydrogens(initial_prot)
    spruce.StandardizeAndFilter(initial_prot, grid, metadata)

    # Re-percieve residues so that atom number and connect records dont get screwed up
    openeye_perceive_residues(initial_prot)

    # If we don't want to return a DU, just return the spruced protein
    if not return_du:
        return initial_prot

    if site_residue:
        dus = list(
            oespruce.OEMakeDesignUnits(initial_prot, metadata, opts, site_residue)
        )
    else:
        dus = list(oespruce.OEMakeDesignUnits(initial_prot, metadata, opts))
    try:
        du = dus[0]
        if not du.HasProtein():
            raise ValueError(f"Resulting design unit '{du.GetTitle()}' has no protein.")
        if not site_residue and not du.HasLigand():
            raise ValueError(f"Resulting design unit '{du.GetTitle()}' has no ligand.")
        # Generate docking receptor for each DU
        oedocking.OEMakeReceptor(du)

        return du

    except IndexError:
        return initial_prot


def superpose_molecule(ref_mol, mobile_mol, ref_chain="A", mobile_chain="A"):
    """
    Superpose `mobile_mol` onto `ref_mol`.

    Parameters
    ----------
    ref_mol : oechem.OEGraphMol
        Reference molecule to align to.
    mobile_mol : oechem.OEGraphMol
        Molecule to align.
    ref_chain : Reference chain to align to
    mobile_chain : Mobile chain to use for alignment (the whole molecule will move as well though)

    Returns
    -------
    oechem.OEGraphMol
        New aligned molecule.
    float
        RMSD between `ref_mol` and `mobile_mol` after alignment.
    """

    # Default atom predicates
    if ref_chain not in find_component_chains(ref_mol, "protein"):
        raise ValueError(f"Chain {ref_chain} not found in reference molecule.")
    if mobile_chain not in find_component_chains(mobile_mol, "protein"):
        raise ValueError(f"Chain {mobile_chain} not found in mobile molecule.")

    ref_pred = oechem.OEHasChainID(ref_chain)
    mobile_pred = oechem.OEHasChainID(mobile_chain)

    # Create object to store results
    aln_res = oespruce.OESuperposeResults()

    # Set up superposing object and set reference molecule
    superpos = oespruce.OESuperpose()
    superpos.SetupRef(ref_mol, ref_pred)

    # Perform superposing
    superpos.Superpose(aln_res, mobile_mol, mobile_pred)
    # print(f"RMSD: {aln_res.GetRMSD()}")

    # Create copy of molecule and transform it to the aligned position
    mobile_mol_aligned = mobile_mol.CreateCopy()
    aln_res.Transform(mobile_mol_aligned)

    return mobile_mol_aligned, aln_res.GetRMSD()


def mutate_residues(input_mol, res_list, protein_chains=None, place_h=True):
    """
    Mutate residues in the input molecule using OpenEye.
    TODO: Make this more robust using some kind of sequence alignment.

    Parameters
    ----------
    input_mol : oechem.OEGraphMol
        Input OpenEye molecule
    res_list : List[str]
        List of 3 letter codes for the full sequence of `input_mol`. Must have
        exactly the same number of residues or this will fail
    place_h : bool, default=True
        Whether to place hydrogen atoms

    Returns
    -------
    oechem.OEGraphMol
        Newly mutated molecule
    """
    # Create a copy of the molecule to avoid modifying original molecule
    mut_prot = input_mol.CreateCopy()
    # Get sequence of input protein
    input_mol_chain = [r.GetExtChainID() for r in oechem.OEGetResidues(input_mol)]
    input_mol_seq = [r.GetName() for r in oechem.OEGetResidues(input_mol)]
    input_mol_num = [r.GetResidueNumber() for r in oechem.OEGetResidues(input_mol)]

    # Build mutation map from OEResidue to new res name by indexing from res num
    mut_map = {}
    for old_res_name, res_num, chain, r in zip(
        input_mol_seq,
        input_mol_num,
        input_mol_chain,
        oechem.OEGetResidues(mut_prot),
    ):
        # Skip if not in identified protein chains
        if protein_chains:
            if chain not in protein_chains:
                continue
        # Skip if we're looking at a water
        if old_res_name == "HOH":
            continue
        try:
            new_res = res_list[res_num - 1]
        except IndexError:
            # If the residue number is out of range (because its a water or something
            # weird) then we can skip right on by it
            continue
        if new_res != old_res_name:
            print(res_num, old_res_name, new_res)
            mut_map[r] = new_res

    # Return early if no mutations found
    if len(mut_map) == 0:
        print("No mutations found", flush=True)
        return input_mol

    # Mutate and build sidechains
    oespruce.OEMutateResidues(mut_prot, mut_map)

    # Place hydrogens
    if place_h:
        oechem.OEPlaceHydrogens(mut_prot)

    # Re-percieve residues so that atom number and connect records dont get screwed up
    openeye_perceive_residues(mut_prot)

    return mut_prot


def build_dimer_from_monomer(prot):
    # Build monomer into dimer as necessary (will need to handle
    #  re-labeling chains since the monomer seems to get the chainID C)
    # Shouldn't affect the protein if the dimer has already been built
    bus = list(oespruce.OEExtractBioUnits(prot))

    # Need to cast to OEGraphMol bc returned type is OEMolBase, which
    #  doesn't pickle
    prot = oechem.OEGraphMol(bus[0])

    # Keep track of chain IDs
    all_chain_ids = {
        r.GetExtChainID()
        for r in oechem.OEGetResidues(prot)
        if all([not oechem.OEIsWater()(a) for a in oechem.OEGetResidueAtoms(prot, r)])
    }
    if len(all_chain_ids) != 2:
        raise AssertionError(f"Chains: {all_chain_ids}")

    print(all_chain_ids)
    return prot


def find_component_chains(mol: oechem.OEMolBase, component: str, res_name=None):
    molcomp = MoleculeComponent(component)
    if res_name:
        chainids = sorted(
            {
                res.GetChainID()
                for res in oechem.OEGetResidues(mol)
                if res.GetName() == res_name
            }
        )
    elif molcomp.name == MoleculeComponent.PROTEIN.name:
        chainids = sorted(
            {
                res.GetChainID()
                for res in oechem.OEGetResidues(mol)
                if oechem.OEIsStandardProteinResidue(res)
            }
        )
    elif molcomp.name == MoleculeComponent.LIGAND.name:
        chainids = sorted(
            {
                res.GetChainID()
                for res in oechem.OEGetResidues(mol)
                if res.IsHetAtom() and not res.GetName() == "HOH"
            }
        )
    return chainids


def check_completed(d, prefix):
    """
    Check if this prep process has already been run successfully in the given
    directory.

    Parameters
    ----------
    d : str
        Directory to check.

    Returns
    -------
    bool
        True if both files exist and can be loaded, otherwise False.
    """

    if (not os.path.isfile(os.path.join(d, f"{prefix}_prepped_receptor_0.oedu"))) or (
        not os.path.isfile(os.path.join(d, f"{prefix}_prepped_receptor_0.pdb"))
    ):
        return False

    try:
        du = oechem.OEDesignUnit()
        oechem.OEReadDesignUnit(
            os.path.join(d, f"{prefix}_prepped_receptor_0.oedu"), du
        )
    except Exception:
        return False

    try:
        _ = load_openeye_pdb(os.path.join(d, f"{prefix}_prepped_receptor_0.pdb"))
    except Exception:
        return False

    return True


def split_openeye_mol(
    complex_mol,
    molecule_filter: Union[str, list[str], MoleculeFilter],
    prot_cutoff_len=10,
) -> namedtuple:
    """
    Split an OpenEye-loaded molecule into protein, ligand, etc.
    Uses the OpenEye OESplitMolComplex function, which automatically splits out
    only the first ligand binding site it sees.

    Parameters
    ----------
    complex_mol : oechem.OEMolBase
        Complex molecule to split.
    molecule_filter : MoleculeFilter
        Molecule filter object that contains the filter criteria.
    prot_cutoff_len : int, default=10
        Minimum number of residues in a protein chain required in order to keep

    Returns
    -------
    namedtuple
        A namedtuple containing the protein, ligand, and water molecules.
    """
    # These are the objects that will be returned at the end
    lig_mol = oechem.OEGraphMol()
    prot_mol = oechem.OEGraphMol()
    water_mol = oechem.OEGraphMol()
    oth_mol = oechem.OEGraphMol()

    if type(molecule_filter) == str:
        molecule_filter = MoleculeFilter(components_to_keep=[molecule_filter])
    elif type(molecule_filter) == list:
        molecule_filter = MoleculeFilter(components_to_keep=molecule_filter)
    else:
        molecule_filter = molecule_filter

    # Make splitting split out covalent ligands possible
    # TODO: look into different covalent-related options here
    opts = oechem.OESplitMolComplexOptions()
    opts.SetSplitCovalent(True)
    opts.SetSplitCovalentCofactors(True)

    # Protein splitting options
    complex_filter = []
    if "protein" in molecule_filter.components_to_keep:
        prot_only = oechem.OEMolComplexFilterFactory(
            oechem.OEMolComplexFilterCategory_Protein
        )
        if len(molecule_filter.protein_chains) > 0:
            chain_filters = [
                oechem.OERoleMolComplexFilterFactory(
                    oechem.OEMolComplexChainRoleFactory(chain)
                )
                for chain in molecule_filter.protein_chains
            ]

            chain_filter = reduce(oechem.OEOrRoleSet, chain_filters)
            prot_filter = oechem.OEAndRoleSet(prot_only, chain_filter)
        else:
            prot_filter = prot_only
        opts.SetProteinFilter(prot_filter)
        complex_filter.append(prot_filter)
    # Ligand splitting options
    # Select ligand as all residues with resn LIG
    if "ligand" in molecule_filter.components_to_keep:
        lig_only = oechem.OEMolComplexFilterFactory(
            oechem.OEMolComplexFilterCategory_Ligand
        )
        if molecule_filter.ligand_chain is None:
            lig_filter = lig_only
        else:
            lig_chain = oechem.OERoleMolComplexFilterFactory(
                oechem.OEMolComplexChainRoleFactory(molecule_filter.ligand_chain)
            )
            lig_filter = oechem.OEAndRoleSet(lig_only, lig_chain)
        opts.SetLigandFilter(lig_filter)
        complex_filter.append(lig_filter)

    if "water" in molecule_filter.components_to_keep:
        water_filter = oechem.OEMolComplexFilterFactory(
            oechem.OEMolComplexFilterCategory_Water
        )
        complex_filter.append(water_filter)

    if len(complex_filter) == 0:
        raise RuntimeError(
            "No components to keep were specified. Maybe OpenEye wackiness?"
        )
    # Use python 'reduce' to combine all the filters into one, otherwise OpenEye will throw an error
    opts.SetProteinFilter(reduce(oechem.OEOrRoleSet, complex_filter))
    oechem.OESplitMolComplex(
        lig_mol,
        prot_mol,
        water_mol,
        oth_mol,
        complex_mol,
        opts,
    )
    # TODO: make this nicer?
    # This is a bit of a hack. If we don't want to keep the ligand, trim_small_chains makes sure
    # that small peptides which are acting as ligands make it into the final
    # But it will also remove ligands itself (I guess). So if we do want to keep the ligand
    # then we don't want to use it.
    if (
        "protein" in molecule_filter.components_to_keep
        and "ligand" not in molecule_filter.components_to_keep
    ):
        prot_mol = trim_small_chains(prot_mol, prot_cutoff_len)
    return prot_mol


def split_openeye_design_unit(du, lig=None, lig_title=None):
    """
    Parameters
    ----------
    du : oechem.OEDesignUnit
        Design Unit to be saved
    lig : oechem.OEGraphMol, optional

    lig_title : str, optional
        ID of Ligand to be saved to the Title tag in the SDF, by default None
    include_solvent : bool, optional
        Whether to include solvent in the complex, by default True

    Returns
    -------
    lig : oechem.OEGraphMol
        OE object containing ligand
    protein : oechem.OEGraphMol
        OE object containing only protein
    complex : oechem.OEGraphMol
        OE object containing ligand + protein
    """
    prot = oechem.OEGraphMol()
    complex_ = oechem.OEGraphMol()
    # complex_ = du_to_complex(du, include_solvent=include_solvent)
    du.GetProtein(prot)
    if not lig:
        lig = oechem.OEGraphMol()
        du.GetLigand(lig)

    # Set ligand title, useful for the combined sdf file
    if lig_title:
        lig.SetTitle(f"{lig_title}")

    # Give ligand atoms their own chain "L" and set the resname to "LIG"
    residue = oechem.OEAtomGetResidue(next(iter(lig.GetAtoms())))
    residue.SetChainID("L")
    residue.SetName("LIG")
    residue.SetHetAtom(True)
    for atom in list(lig.GetAtoms()):
        oechem.OEAtomSetResidue(atom, residue)

    # Combine protein and ligand and save
    # TODO: consider saving water as well
    oechem.OEAddMols(complex_, prot)
    oechem.OEAddMols(complex_, lig)

    # Clean up PDB info by re-perceiving, perserving chain ID,
    # residue number, and residue name
    openeye_perceive_residues(prot)
    openeye_perceive_residues(complex_)
    return lig, prot, complex_


def du_to_complex(du, include_solvent=False):
    """
    Convert OEDesignUnit to OEGraphMol containing the protein and ligand from
    `du`.

    Parameters
    ----------
    du : oechem.OEDesignUnit
        OEDesignUnit object to extract from.
    include_solvent : bool, default=False
        Whether to include solvent molecules.

    Returns
    -------
    oechem.OEGraphMol
        Molecule with protein and ligand from `du`
    """
    complex_mol = oechem.OEGraphMol()
    comp_tag = (
        oechem.OEDesignUnitComponents_Protein | oechem.OEDesignUnitComponents_Ligand
    )
    if include_solvent:
        comp_tag |= oechem.OEDesignUnitComponents_Solvent
    du.GetComponents(complex_mol, comp_tag)

    complex_mol = openeye_perceive_residues(complex_mol)

    return complex_mol


def trim_small_chains(input_mol, cutoff_len=10):
    """
    Remove short chains from a protein molecule object. The goal is to get rid
    of any peptide ligands that were mistakenly collected by OESplitMolComplex.

    Parameters
    ----------
    input_mol : oechem.OEGraphMol
        OEGraphMol object containing the protein to trim
    cutoff_len : int, default=10
        The cutoff length for peptide chains (chains must have more than this
        many residues to be included)

    Returns
    -------
    oechem.OEGraphMol
        Trimmed molecule
    """
    # Copy the molecule
    mol_copy = input_mol.CreateCopy()

    # Remove chains from mol_copy that are too short (possibly a better way of
    #  doing this with OpenEye functions)
    # Get number of residues per chain
    chain_len_dict = {}
    hv = oechem.OEHierView(mol_copy)
    for chain in hv.GetChains():
        chain_id = chain.GetChainID()
        for frag in chain.GetFragments():
            frag_len = len(list(frag.GetResidues()))
            try:
                chain_len_dict[chain_id] += frag_len
            except KeyError:
                chain_len_dict[chain_id] = frag_len

    # Remove short chains atom by atom
    for a in mol_copy.GetAtoms():
        chain_id = oechem.OEAtomGetResidue(a).GetExtChainID()
        if (chain_id not in chain_len_dict) or (chain_len_dict[chain_id] <= cutoff_len):
            mol_copy.DeleteAtom(a)

    return mol_copy
